TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------

DBD = anc350AsynMotor.dbd

LIBRARY = anc350AsynMotor
anc350AsynMotor_SRCS = anc350AsynMotor.c anc350AsynMotorRegister.cc

include $(TOP)/configure/RULES
