TOP=../..
include $(TOP)/configure/CONFIG

DATA += anc350Main.edl

install:
	mkdir -p $(TOP)/data
	cp -f $(TOP)/ancTest350App/edl/anc350Main.edl $(TOP)/data/anc350Main.edl

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

